### ISSUE TITLE
assert self.map.shape[0] == self.map.shape[1], "Map is not a distance matrix!"

### ISSUE THREAD

**Issue by ernara** [johnberroa/Ant-Colony-Optimization#1]
You can put any matrix and you still get this shit answer.

**Comment by georgesakarellos** [comment]
Hi ernara!
from AntColonyOptimizer import AntColonyOptimizer
import numpy as np
problem = some_distance_matrix

problem = np.array(problem)
optimizer = AntColonyOptimizer(ants=1, evaporation_rate=.1, intensification=2, alpha=1, beta=1,
beta_evaporation_rate=0, choose_best=.1)

best = optimizer.fit(problem, 100)
optimizer.plot()

**Comment by erickson337** [comment]
Exemple problem:

     problem = np.array([[0,10,12,11,14]
            ,[10,0,13,15,8]
            ,[12,13,0,9,14]
            ,[11,15,9,0,16]
            ,[14,8,14,16,0]])

**Comment by johnberroa** [comment]
Hi @ernara, this means you are not putting a square matrix into the optimizer. 
Calling `map.shape` should yield something like `(x, x)`, where `x` is how many rows/columns you have.
